# Generated by Django 4.2.5 on 2024-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_alter_profile_phone_number_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default={'+254714805460'}, max_length=15),
        ),
    ]
